//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef _LIBSYCL_DEVICE_BINARY_STRUCTURES
#define _LIBSYCL_DEVICE_BINARY_STRUCTURES

#include "llvm/BinaryFormat/Offload.h"
#include <cstdint>

// Make offload types available without namespace qualification
using llvm::offload::OffloadKind;
using llvm::offload::ImageKind;
using llvm::offload::EntryTy;
using llvm::offload::OFK_None;
using llvm::offload::OFK_OpenMP;
using llvm::offload::OFK_Cuda;
using llvm::offload::OFK_HIP;
using llvm::offload::OFK_SYCL;
using llvm::offload::OFK_LAST;
using llvm::offload::IMG_None;
using llvm::offload::IMG_Object;
using llvm::offload::IMG_Bitcode;
using llvm::offload::IMG_Cubin;
using llvm::offload::IMG_Fatbinary;
using llvm::offload::IMG_PTX;
using llvm::offload::IMG_SPIRV;
using llvm::offload::IMG_LAST;

/// Target identification strings.
///
/// A device type represented by a particular target
/// triple requires specific binary images. We need
/// to map the image type onto the device target triple.

/// Unknown target.
#define _LIBSYCL_DEVICE_BINARY_TARGET_TRIPLE_UNKNOWN "unknown-unknown-unknown"
/// SPIR-V with 64-bit pointers.
#define _LIBSYCL_DEVICE_BINARY_TARGET_SPIRV64 "spirv64-unknown-unknown"

/// Device binary descriptor version supported by this library.
static const uint16_t _LIBSYCL_SUPPORTED_DEVICE_BINARY_VERSION = 3;

/// This struct is a record of the device binary information.
///  It must match the __tgt_device_image structure generated by the
///  clang-offload-wrapper tool when their `Version` field match.
struct __sycl_tgt_device_image {
  uint16_t Version;
  /// The type of offload model the binary employs. See llvm::offload::OffloadKind.
  /// Only OFK_SYCL is supported by libsycl.
  uint8_t OffloadKind;
  /// Format of the binary data, see llvm::offload::ImageKind.
  uint8_t ImageFormat;
  /// A null-terminated string representation of the device's target
  /// architecture. Must hold one of _LIBSYCL_DEVICE_BINARY_TARGET_* values.
  const char *TripleString;
  /// A null-terminated string; target- and compiler-specific options
  /// which are suggested to use to "compile" program at runtime.
  const char *CompileOptions;
  /// A null-terminated string; target- and compiler-specific options
  /// which are suggested to use to "link" program at runtime.
  const char *LinkOptions;
  /// Pointer to the target code start.
  const unsigned char *ImageStart;
  /// Pointer to the target code end.
  const unsigned char *ImageEnd;
  /// The offload entry table
  EntryTy *EntriesBegin;
  EntryTy *EntriesEnd;
  // TODO: properties are not supported now.
  /// Array of preperty sets.
  void *PropertiesBegin;
  void *PropertiesEnd;
};

/// Version of offload binaries descriptor `__sycl_tgt_bin_desc` supported by
/// libsycl.
static constexpr uint16_t _LIBSYCL_SUPPORTED_OFFLOAD_BINARY_VERSION = 1;

/// This struct is a record of all the device code that may be offloaded.
/// It must match the `__tgt_bin_desc` structure generated by
/// the clang-offload-wrapper tool when their `Version` field match.
struct __sycl_tgt_bin_desc {
  /// Version of the structure.
  uint16_t Version;
  /// Number of device binaries in this descriptor.
  uint16_t NumDeviceBinaries;
  /// Device binaries data.
  __sycl_tgt_device_image *DeviceImages;
  /// The offload entry table (not used, for compatibility with OpenMP).
  EntryTy *HostEntriesBegin;
  EntryTy *HostEntriesEnd;
};

#endif // _LIBSYCL_DEVICE_BINARY_STRUCTURES
